
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "marcalph", email = "marcalph@protonmail.com"},
]
dependencies = [
    "torch>=2.0.1",
    "pytorch-lightning>=2.0.4",
    "torchvision>=0.15.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}


