[tool.poetry]
name = "learning"
version = "0.1.0"
description = ""
authors = ["Marc Alphonsus <<marc.alphonsus@helsing.ai>>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pycocotools = "^2.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
