apiVersion: v1
kind: Pod
metadata:
  name: happyelephant
  namespace: happynamespace
  labels: 
    company: mycompany    
spec:
  containers:
  - name: red
    image: redis
    ports:
    - name: redport
      containerPort: 8080
      protocol: TCP
  nodeSelector:
    disk: ssd




