apiVersion: v1
kind: Pod
metadata:
  name: sharepod
  labels: 
    app: sharepod
spec: 
  volumes:
  - name: hostvol
    hostPath:
      path: /home/docker/pod-volume
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: hostvol
  - image: debian
    name: debian
    volumeMounts: 
    - mountPath: /hostvol
      name: hostvol
    command: ["/bin/sh", "-c", "echo intro to k8s > /hostvol/index.html; sleep 3600"]
